### ISSUE TITLE
Calling Convention behavior in bca65cd introduces parameter mismatch

### ISSUE THREAD

**Issue by ehennenfent** [Vector35/binaryninja-api#739]
In version 1.0.816-dev, the following traceback can be observed:
```
>>> bv.arch.calling_conventions
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ehennenfent/binaryninja/plugins/../python/binaryninja/architecture.py", line 364, in calling_conventions
    obj = callingconvention.CallingConvention(None, core.BNNewCallingConventionReference(cc[i]))
  File "/home/ehennenfent/binaryninja/plugins/../python/binaryninja/callingconvention.py", line 58, in __init__
    self.handle = core.BNCreateCallingConvention(arch.handle, name, self._cb)
AttributeError: 'NoneType' object has no attribute 'handle'
>>> bv.arch
<arch: x86_64>
```

[Line 364 in architecture.py](https://github.com/Vector35/binaryninja-api/blob/dev/python/architecture.py#L364) attempts to instantiate a new calling convention object. Before the changes introduced in bca65cd, the result of `core.BNNewCallingConventionReference(cc[i])`  was passed as the `handle` parameter. However, the additional argument to the constructor means that `handle` is now `None` when the calling convention object is instantiated, which results in the incorrect code path being followed, producing the exception.

Edit: this traceback can also be observed from `bv.platform.calling_conventions`, `bv.arch.standalone_platform.default_calling_convention`, `bv.platform.system_call_convention`, etc.

**Comment by plafosse** [comment]
Thanks for the report, fixed in dev 817
